[package]
name = "advent_of_code_template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
rustc-hash = "2.1.0"
itertools = "0.13.0"
pathfinding = "4.12.0"
rayon = "1.10.0"
